name: Run the qodo-cover action

on:
  pull_request:
    branches:
      - main
    types:
      - opened  # Trigger only when a pull request is opened

permissions:
  pull-requests: write  # Allows commenting on pull requests
  contents: write  # Allows reading and writing files

jobs:
  run-qodo-cover:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov fastapi httpx

      - name: Verify SQLite version
        run: sqlite3 --version

      - name: qodo-cover
        uses: qododavid/capa/.github/actions/qodo-cover@v1
        with:
          greeting: Hi there
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_language: python
          project_root: templated_tests/python_fastapi
          code_coverage_report_path: templated_tests/python_fastapi/coverage.xml
          test_command: "pytest --cov=. --cov-report=xml --cov-report=term"
          model: gpt-4o

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
