name: Run the qodo-cover action

on:
  pull_request:
    branches:
      - main
    types:
      - opened  # Trigger only when a pull request is opened

permissions:
  pull-requests: write  # Allows commenting on pull requests
  contents: write  # Allows reading and writing files

jobs:
  pr-diff-and-line-count:
    runs-on: ubuntu-latest
    steps:
      - name: qodo-cover
        uses: qododavid/capa/.github/actions/qodo-cover@v1
        with:
          greeting: "Hi there"
          github_token: ${{ secrets.GITHUB_TOKEN }}